### ISSUE TITLE
Can you add a startup item?

### ISSUE THREAD

**Issue by Offline-945** [elight2/ClevoFanControl#1]
Very nice software！But this program need to start it manually every time, so can you add the boot startup options？

**Comment by elight2** [comment]
Sorry for my poor English, I have actually written how to make it start up automatically on boot in Linux in the README file, but only in Chinese. I will update the English version of the README later.
My current solution for autostart:
1. Create a `.sh` file under the same directory of the gui app, which `sleep` for some seconds (to wait the desktop session to initialize) and then `nohup bash -c 'sudo ./ClevoFanControl-gui & > /dev/null'.
2. Write a `.desktop` file whose `Exec` entry is set to the `.sh` script.
3. Add the `.desktop` file to xdg autostart.
4. Add an exception rule in `/etc/sudoers` that allows `ClevoFanControl-gui` to run as root without requiring password.

**Comment by Offline-945** [comment]
😂如果在windows下怎么开机自启呢，我尝试过添加任务计划程序，但开机后无法显示托盘图标，不知道有什么解决方法

**Comment by Offline-945** [comment]
而且必须手动使用管理员权限运行，直接双击打开的话不起作用

**Comment by elight2** [comment]
用任务计划程序添加一个自定义计划，执行的操作设置成运行软件的exe，设置最高权限启动，触发器添加一个登录时运行，程序运行目录设置到exe目录防止找不到ico图标

**Comment by Offline-945** [comment]
收到，我试试



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 25, 2024 08:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [elight2/ClevoFanControl] Can you add a startup item? (Issue #1)




 
用任务计划程序添加一个自定义计划，执行的操作设置成运行软件的exe，设置最高权限启动，触发器添加一个登录时运行，程序运行目录设置到exe目录防止找不到ico图标

**Comment by Offline-945** [comment]
我是这样设置的，还是不显示图标
![image](https://github.com/user-attachments/assets/1758e2d7-81a9-4618-9f1c-5ad69096650a)
![image](https://github.com/user-attachments/assets/c269838e-b8fe-4723-88dd-9604b7a6087e)
![image](https://github.com/user-attachments/assets/0089d4c5-f476-4186-b0c6-8d6cf2145d90)

**Comment by elight2** [comment]
你这个应该不是没有图标，软件就没启动，触发器用启动时不行的，要选用户登录时

**Comment by Offline-945** [comment]
软件在任务管理器里可以看到，也有效果，就是没托盘图标，我再试试登录时启动



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 25, 2024 13:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [elight2/ClevoFanControl] Can you add a startup item? (Issue #1)




 
你这个应该不是没有图标，软件就没启动，触发器用启动时不行的，要选用户登录时

**Comment by Offline-945** [comment]
成功了，感谢😍
